the_user/urls.py
from django.urls import re_path, path
from . import views

from .views_otp import ask_for_otp,setting_two_factor 

app_name = 'the_user'
urlpatterns = [

    path("", views.landing_page, name="landing_page"),
    path("settings/", views.setting, name="settings"),
    path("settings/twofactor/", setting_two_factor, name="setting_two_factor"),
    path("twofactor/", ask_for_otp, name="ask_for_otp"),
 

    # re_path(r'^totp/create/$', views.TOTPCreateView.as_view(), name='totp-create'),
    # re_path(r'^totp/login/(?P<token>[0-9]{6})/$', views.TOTPVerifyView.as_view(), name='totp-login'),
]

the_user/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django.core.validators import RegexValidator
 
from django.utils import translation 

import logging
logger = logging.getLogger('ilogger')
# Create your models here.
phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                             message="Phone number must be entered in the format: '+999999999'. Up to 15 digits "
                                     "allowed.")


# --------------------------------------------------------------------------------
#
# --------------------------------------------------------------------------------
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,verbose_name=_("User"),
                                related_name="profile",
                                primary_key=True)

    website_language = models.CharField(max_length=2, choices=settings.LANGUAGES, default='en')
    communication_language = models.CharField(max_length=2, choices=settings.LANGUAGES, default='en')

    force_password_change = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


    #----------------------------------------------------------------
    def get_change_password_url(self):
        from django.urls import reverse
        return reverse('account_change_password')

    # def set_language(self,request):
    #     translation.activate(self.language) 

    #     request.session[LANGUAGE_SESSION_KEY] = self.language
    #     request.session.save()
# # --------------------------------------------------------------------------------
# #
# # --------------------------------------------------------------------------------
# class Address(models.Model):
#     class Types(models.TextChoices):
#         HOME = 'H', _('Home')
#         SHIPPING = 'S', _('Shipping')
#         OFFICE = 'O', _('Office')
#         BILLING = 'B', _('Billing')
#
#
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='addresses')
#     # profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='addresses')
#
#     type = models.CharField(max_length=1, choices=Types.choices, default=Types.HOME)
#     address1 = models.CharField(max_length=50)
#     address2 = models.CharField(max_length=50, blank=True)
#     city = models.CharField(max_length=50)
#     state = models.CharField(max_length=50)
#     postcode = models.CharField(max_length=10)
#     country = models.CharField(max_length=3, choices=ISO_3166_CODES)
#     created_date = models.DateTimeField(auto_now_add=True)
#     modified_date = models.DateTimeField(auto_now=True)
#     def clean(self):
#         # Ensure postcodes are valid for country
#         self.ensure_postcode_is_valid_for_country()
#
#     def ensure_postcode_is_valid_for_country(self):
#         """
#         Validate postcode given the country
#         """
#
#
#         if self.postcode and self.country:
#             # Ensure postcodes are always uppercase
#             postcode = self.postcode.upper().replace(' ', '')
#
#             regex = self.POSTCODES_REGEX.get(self.country, None)
#
#             # Validate postcode against regex for the country if available
#             if regex and not re.match(regex, postcode):
#                 msg = _("The postcode '%(postcode)s' is not valid "
#                         "for %(country)s") \
#                       % {'postcode': self.postcode,
#                          'country': self.country}
#                 raise exceptions.ValidationError(
#                     {'postcode': [msg]})
#
#     def __str__(self):
#         return '{}:{}'.format(Address.Types(self.type).label, self.address1)
# --------------------------------------------------------------------------------
#
# --------------------------------------------------------------------------------

class BooleanSettings(models.Model):
    class AllowedSettings(models.TextChoices):
        TWO_FACTOR = 'TWO_FACTOR', _('Enable Two-Factor authentication?')
        GENERATE_INVOICE = 'GENERATE_INVOICE', _('Generate invoice for each Transaction?')

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             related_name="booleansettings",
                             null=False, blank=False, verbose_name=_("User")
                             )
    key = models.CharField(max_length=50, choices=AllowedSettings.choices, null=False, blank=False,
                           verbose_name="Setting")
    value = models.BooleanField(verbose_name="Enabled", default=False, blank=False, null=False )

    class Meta:
        ordering = ['user', 'key']
        constraints = [
            models.UniqueConstraint(fields=['user', 'key'], name='User unique Setting')
        ]

    def __str__(self):
        return self.key;

    @staticmethod
    def load(user):
        for setting in BooleanSettings.AllowedSettings:
            boolean_setting = BooleanSettings.objects.filter(user=user).filter(key=setting).first()
            if not boolean_setting:
                boolean_setting = BooleanSettings(user=user, key=setting)
                boolean_setting.save()

the_user/templates/the_user/otp.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account  %}

{% load static %}
{% load crispy_forms_tags %}


{% block content %}


<!-- LOGIN -->
<div class="card p-4">
    <div class="card-body">

      
        <h1>{% trans 'Please enter OTP' %}</h1>
        <p class="text-muted">{% blocktrans %} "Good job! Always better to be secure then sorry." {% endblocktrans %}</p>
        {% include 'messages.html' %}


        <form class="user" method="POST" action="">
            {% csrf_token %}
            {{ form|crispy }}


            <div class="row">
                <div class="col-12">
                    <button class="btn btn-primary px-4" type="submit">{% trans 'Verify' %}</button>
                </div>

            </div>
        </form>
    </div>
</div>
<!-- end login -->


<div class="card text-white bg-primary py-5 d-md-down-none" style="width:44%">
    <div class="card-body text-center">
        <div>
            <h2>{% blocktrans %}Use your Google Authenticator app to get your token. {% endblocktrans %}</h2>


        </div>
    </div>
</div>
{% endblock %}

the_user/templates/the_user/setting_two_factor.html
{% extends "the_user/settings.html" %}

{% load i18n %}

{% block head_title %}{% trans "User setting_two_factor_two_factors" %}{% endblock %}

{% block settingdata %}
<div id="app_twofactor_div">

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header"><Strong>{% trans "What is Two-Factor authentication?" %}</Strong></div>
                <div class="card-body">
                    <ol>
                        <li>
                            Two-factor authentication is an extra layer of security for your {{app_name}} Account.
                           
                        </li>
                        <li>
                            After you turn it on, signing into your account will require both your regular password and
                            a 6-digit one-time verification code.<br />
                        </li>
                        <li>
                            A mobile device is required. Using this security feature requires a mobile device capable of
                            scanning a QR code using Google or Microsoft authenticator application.
                        </li>

                    </ol>

                </div>
            </div>
        </div>

    </div>

    <div class="row">

        <!-- LOGIN -->
        <div class="col-lg">
            <div class="card">
                <div class="card-header"><Strong>{% trans "Two-Factor Authentication" %}</Strong></div>
                <div class="card-body">


                    <div class="list-group list-group-accent">
                        <div
                            class="list-group-item list-group-item-accent-{% if setting_two_factor.value %}success {% else %}warning {% endif %}   list-group-item-divider">
                            <div class="row">
                                <div class="col-sm-9 ">
                                    {{ setting_two_factor.get_key_display }}
                                    <div><small class="text-muted">{% trans "For extra layer of security." %}</small>
                                    </div>

                                </div>
                                <div class="col-sm-3">
                                    <form method="POST" onsubmit="show_processing_model()">
                                        {% csrf_token %}
                                        <label class="c-switch c-switch-label c-switch-opposite-primary">
                                            <input onChange="this.form.submit()" name={{setting_two_factor.key}}
                                                class="c-switch-input" type="checkbox" {% if setting_two_factor.value %}
                                                checked {% endif %}>
                                            <span class="c-switch-slider" data-checked="✓" data-unchecked="✕"></span>
                                            <input type="hidden" name="change2fs" value="Y">
                                        </label>
                                    </form>
                                </div>
                            </div>
                        </div>

                        <div class="list-group-item list-group-item-accent-danger  list-group-item-divider">
                            <div class="row">
                                <div class="col-sm-9 ">
                                    {% trans 'Get a new Two-Factor QR Code?' %}
                                    <div><small class="text-muted">{% trans "Just in case." %}</small></div>

                                </div>
                                <div class="col-sm-3">
                                    <button type="button" v-on:click="getNewQRCode"
                                        class="btn btn-primary px-4 c-loading-button" data-coreui="loading-button"
                                        data-timeout="500" data-progress="true">
                                        {% trans "Yes" %}
                                    </button>

                                </div>
                            </div>
                        </div>
                    </div>


                </div>

            </div>
        </div>
    </div>
    <div class="row">
        {% if setting_two_factor.value %}
        <div class="col-lg">

            <div class="card">
                <div class="card-header"><Strong>{% trans "Scan the QR Code with Google or Microsoft Authenticator app" %}</Strong>
                </div>
                <div class="card-body">

                    <div class="row">
                        <div class="col">
                            <img class="img-fluid"
                                src="https://www.google.com/chart?chs=200x200&chld=M|0&cht=qr&chl={{qr_code_url}}issuer%3D{{app_name}}"></img>

                            <hr>

                            <h5>{% trans "Activate it here" %}</h5>

                            <form method="POST" onsubmit="show_processing_model()" class="w-100">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-12">
                                        <input v-model="token" placeholder="the 6 digit code" type="number" max="999999"
                                            class="form-control"
                                            v-bind:class="{ 'is-valid': verified, 'is-invalid': notverified }" />
                                        <div class="invalid-feedback">
                                            {% trans "Please Enter a correct code." %}
                                        </div>
                                        <div class="valid-feedback">
                                            {% trans "Looks good!" %}
                                        </div>
                                    </div>
                                </div>
                                <br>
                                <div class="row">
                                    <div class="col-12">
                                        <button @click="submitform" type="button"
                                            class="btn btn-primary px-4 ">{% trans "Verify" %}
                                        </button>
                                    </div>
                                </div>


                            </form>
                            <hr>


                        </div>





                        <div class="col">
                            <div class="c-callout "><small class="text-muted">Step 1</small>
                                <div class="text-value-sm">Install the Google or Microsoft Authenticator app on your mobile device
                                </div>
                                <hr>
                            </div>
                            <div class="c-callout  "><small class="text-muted">Step 2</small>
                                <div class="text-value-sm">Scan this QR Code</div>
                                <hr>
                            </div>
                            <div class="c-callout "><small class="text-muted">Step 3</small>
                                <div class="text-value-sm">Input the 6-digit code that the Google or Microsoft Authenticator app
                                    provided
                                    below.





                                </div>
                                <hr>
                            </div>



                        </div>
                    </div>

                </div>

            </div>

        </div>
        {% endif %}
    </div>
</div>

{% endblock %}


{% block more-js %}
<script>
    let app_twofactor = new Vue({
        el: "#app_twofactor_div",
        delimiters: ['[[', ']]'],
        data: {
            token: '',
            verified: false,
            notverified: false,


        },
      
        methods: {
            getNewQRCode: function (e) {
             

                const csrftoken = Cookies.get('csrftoken');

                let config = {
                    headers: {
                        "X-CSRFToken": csrftoken,
                        "Content-Type": "application/json",
                        "Accept": "application/json"
                    }
                }
                let data = {
                    reset: true,

                }

                var self = this
                axios.post('{% url "internalapi:setting_two_factor_reset" %}', data, config).then(function (
                    response) {
                    // handle success
                    // console.log(response);

                    window.location.reload()

                }).catch(function (error) {
                    // handle error
                    // console.log(error);
                }).then(function () {
                    // always executed
                });

            },

            submitform: function (e) {
          
                const csrftoken = Cookies.get('csrftoken');

                let config = {
                    headers: {
                        "X-CSRFToken": csrftoken,
                        "Content-Type": "application/json",
                        "Accept": "application/json"
                    }
                }
                let data = {
                    token: this.token,

                }

                var self = this
                axios.post('{% url "internalapi:setting_two_factor_verification" %}', data, config).then(
                    function (response) {
                        // handle success
                        // console.log(response);
                        self.verified = response.data.verified


                    }).catch(function (error) {
                    self.verified = false
                    // handle error
                    // console.log(error);
                }).then(function () {
                    // always executed
                    self.notverified = !self.verified
                });


                // e.preventDefault();

            },


        }
    });
</script>



{% endblock more-js %}

the_user/templates/the_user/settings.html
{% extends "base.html" %}

{% load i18n %}

{% block head_title %}{% trans "User settings" %}{% endblock %}

{% block content %}
{% load crispy_forms_tags %}


<div class="container-fluid">
    <!-- LOGIN -->
    <div class="row mt-2">
        <div class="col-lg-3">
            <div class="card">
                <div class="card-header"><Strong>{% trans "User settings" %}</Strong></div>
                <div class="card-body">
                    <ul class="c-sidebar-nav">
                        <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link"
                                                          href="{% url 'the_user:settings' %}">
                            <svg class="c-sidebar-nav-icon">
                                <use xlink:href="{{ STATIC_URL }}coreui/vendors/coreui/icons/svg/free.svg#cil-user"></use>
                            </svg>

                            {% url 'the_user:settings' as url %}
                            {% if url == request.path %}
                            <strong> {% trans 'Profile' %}</strong>
                            {% else %}
                            {% trans 'Profile' %}
                            {% endif %}

                            <!--                        <span class="badge badge-info">NEW</span>-->
                        </a>
                        </li>
                        <li class="c-sidebar-nav-title">{% trans 'Security' %}</li>

                        <li class="c-sidebar-nav-item">
                            <a class="c-sidebar-nav-link" href="{% url 'the_user:setting_two_factor' %}">
                                <svg class="c-sidebar-nav-icon">
                                    <use xlink:href="{{ STATIC_URL }}coreui/vendors/coreui/icons/svg/free.svg#cil-qr-code"></use>
                                </svg>
                                {% url 'the_user:setting_two_factor' as url %}
                                {% if url == request.path %}
                                <strong> {% trans 'Setup Two-Factor' %}</strong>
                                {% else %}
                                {% trans 'Setup Two-Factor' %}
                                {% endif %}

                            </a>
                        </li>

                        <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link"
                                                          href="{% url 'account_change_password'%}">
                            <svg class="c-sidebar-nav-icon">
                                <use xlink:href="{{ STATIC_URL }}coreui/vendors/coreui/icons/svg/free.svg#cil-lock-locked"></use>
                            </svg>
                            {% url 'account_change_password' as url %}
                            {% if url == request.path %}
                            <strong> {% trans 'Change Password' %}</strong>
                            {% else %}
                            {% trans 'Change Password' %}
                            {% endif %}
                        </a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-lg-9">
            {% block settingdata %}


            <div class="row">

                <!-- LOGIN -->
                <div class="col-lg">
                    <div class="card">
                        <div class="card-header"><Strong>{% trans "Update Profile" %}</Strong></div>
                        <div class="card-body">
                            <form method="POST" onsubmit="show_processing_model()" action="">
                                {% csrf_token %}

                                {{ profile_form|crispy }}
                                {{ user_form|crispy }}
                                <div class="row">
                                    <div class="col-12">
                                        <button class="btn btn-primary px-4" type="submit">{% trans 'Save' %}</button>
                                    </div>

                                </div>
                            </form>
                        </div>

                    </div>
                </div>
                </div>




                {% endblock %}

        </div>
    </div>
</div>
{% endblock %}

the_user/templates/the_user/settings_bkp.html
{% extends "base.html" %}

{% load i18n %}

{% block head_title %}{% trans "User settings" %}{% endblock %}

{% block content %}

<br>
<!-- LOGIN -->
<div class="col-sm-12 col-md-6">
    <div class="card">
        <div class="card-header">{% trans "User settings" %}</div>
        <div class="card-body">

            {% for setting in booleansettings %}
            <div class="list-group list-group-accent">
                <div class="list-group-item list-group-item-accent-{% if setting.value %}success {% else %}warning {% endif %}   list-group-item-divider">
                    <div class="row">
                    <div class="col-sm-9 ">
                        {{ setting.get_key_display }}
                    </div>
                    <div class="col-sm-3">
                        <label class="c-switch c-switch-label c-switch-opposite-primary">
                            <input class="c-switch-input" type="checkbox" {% if setting.value %}} checked {% endif %} ><span class="c-switch-slider"
                                                                                                                             data-checked="✓"
                                                                                                                             data-unchecked="✕"></span>
                        </label>
                    </div>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>

    </div>
    </div>


    {% endblock %}